# Generated by Django 3.2.12 on 2022-03-31 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220331_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user_anonymous',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_anonymous_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
