# Generated by Django 3.2.12 on 2022-04-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_rename_answer_1_answersvariants_answer'),
        ('users', '0005_auto_20220331_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='survey',
            field=models.ManyToManyField(to='surveys.Survey'),
        ),
    ]
