# Generated by Django 3.2.12 on 2022-04-01 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_rename_answer_1_answersvariants_answer'),
        ('users', '0010_useractivesurveys'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatusInSurveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('survey', models.ManyToManyField(to='surveys.Survey')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed_surveys',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.DeleteModel(
            name='UserActiveSurveys',
        ),
        migrations.AddField(
            model_name='userstatusinsurveys',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
