# Generated by Django 3.2.12 on 2022-04-05 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220405_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoususeranswer',
            name='user_anonymous',
        ),
        migrations.RemoveField(
            model_name='anonymoususerstatusinsurveys',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='anonymoususeranswer',
            name='user_anonymous_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='users.anonymoususerstatusinsurveys'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
    ]
