version: '3.7'

services:
  web:
    build: ./src
    command: gunicorn questionnaire.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/questionnaire/static
    expose:
      - 8000
    env_file:
      - ./.questionnaire-venv.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/questionnaire/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
