# Generated by Django 3.2.12 on 2022-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='completed_surveys',
            field=models.ManyToManyField(blank=True, to='surveys.Survey'),
        ),
    ]
