# Generated by Django 3.2.12 on 2022-04-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_rename_answer_1_answersvariants_answer'),
        ('users', '0008_alter_useranswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user_anonymous_id',
        ),
        migrations.CreateModel(
            name='AnonymousUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_anonymous_id', models.PositiveIntegerField(default=0)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_choose', models.ManyToManyField(blank=True, to='surveys.AnswersVariants')),
                ('question', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='surveys.question')),
                ('survey', models.ManyToManyField(to='surveys.Survey')),
            ],
        ),
    ]
