# Generated by Django 3.2.12 on 2022-04-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220401_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoususeranswer',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='survey',
        ),
    ]
