# Generated by Django 3.2.12 on 2022-04-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_rename_answer_1_answersvariants_answer'),
        ('users', '0012_auto_20220401_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususeranswer',
            name='survey',
            field=models.ManyToManyField(to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='survey',
            field=models.ManyToManyField(to='surveys.Survey'),
        ),
    ]
