# Generated by Django 3.2.12 on 2022-04-05 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_anonymoususerstatusinsurveys'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='anonymoususeranswer',
            name='user_anonymous_id',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anonymoususeranswer',
            name='user_anonymous',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='users.anonymoususer'),
        ),
        migrations.AddField(
            model_name='anonymoususerstatusinsurveys',
            name='anonymous',
            field=models.ManyToManyField(to='users.AnonymousUser'),
        ),
    ]
