# Generated by Django 3.2.12 on 2022-04-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_rename_answer_answersvariants_answer_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersvariants',
            old_name='answer_1',
            new_name='answer',
        ),
    ]
