# Generated by Django 3.2.12 on 2022-04-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersvariants',
            old_name='answer',
            new_name='answer_1',
        ),
    ]
